# Generated by Django 5.2.8 on 2025-11-17 10:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(choices=[('WEST_AFRICAN_SHORTHORN', 'West African Shorthorn'), ('ZEBU', 'Zebu'), ('SANGA', 'Sanga'), ('CROSSBREED', 'Crossbreed'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('age_months', models.IntegerField(help_text='Age in months (0-300)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(db_index=True, decimal_places=2, help_text='Price in Ghana Cedis (GHS)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_negotiable', models.BooleanField(default=True, help_text='Is the price negotiable?')),
                ('health_status', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=20)),
                ('vaccination_status', models.BooleanField(default=False, help_text='Has the cattle been vaccinated?')),
                ('last_vaccination_date', models.DateField(blank=True, help_text='Date of last vaccination', null=True)),
                ('health_notes', models.TextField(blank=True, help_text='Additional health information')),
                ('feeding_history', models.TextField(blank=True, help_text='Feeding and nutrition history')),
                ('region', models.CharField(choices=[('ASHANTI', 'Ashanti'), ('BRONG_AHAFO', 'Brong Ahafo'), ('CENTRAL', 'Central'), ('EASTERN', 'Eastern'), ('GREATER_ACCRA', 'Greater Accra'), ('NORTHERN', 'Northern'), ('UPPER_EAST', 'Upper East'), ('UPPER_WEST', 'Upper West'), ('VOLTA', 'Volta'), ('WESTERN', 'Western'), ('SAVANNAH', 'Savannah'), ('BONO_EAST', 'Bono East'), ('AHAFO', 'Ahafo'), ('WESTERN_NORTH', 'Western North'), ('NORTH_EAST', 'North East'), ('OTI', 'Oti')], db_index=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location_details', models.TextField(blank=True, help_text='Specific location or directions')),
                ('title', models.CharField(help_text='Short title for the listing', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the cattle')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this listing active?')),
                ('is_sold', models.BooleanField(default=False, help_text='Has this cattle been sold?')),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this listing has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cattle_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cattle',
                'verbose_name_plural': 'Cattle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CattleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Cattle image', upload_to='cattle_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary/featured image?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cattle.cattle')),
            ],
            options={
                'verbose_name': 'Cattle Image',
                'verbose_name_plural': 'Cattle Images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('HEALTH_CERTIFICATE', 'Health Certificate'), ('VACCINATION_RECORD', 'Vaccination Record'), ('VET_REPORT', 'Veterinary Report'), ('OTHER', 'Other Document')], max_length=30)),
                ('document', models.FileField(help_text='PDF or image file', upload_to='health_documents/%Y/%m/%d/')),
                ('document_name', models.CharField(help_text='Name/title of the document', max_length=200)),
                ('issue_date', models.DateField(blank=True, help_text='Date the document was issued', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (if applicable)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_documents', to='cattle.cattle')),
            ],
            options={
                'verbose_name': 'Health Document',
                'verbose_name_plural': 'Health Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(fields=['breed', 'region'], name='cattle_catt_breed_8b1ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(fields=['price', '-created_at'], name='cattle_catt_price_20e5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(fields=['seller', 'is_active'], name='cattle_catt_seller__4a7d53_idx'),
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(fields=['is_active', 'is_sold'], name='cattle_catt_is_acti_8b2c3f_idx'),
        ),
    ]
