# Generated by Django 5.2.8 on 2025-11-17 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True)),
                ('phone_number', models.CharField(db_index=True, help_text='Ghana phone number format', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+233XXXXXXXXX' or '0XXXXXXXXX'", regex='^\\+?233?\\d{9,10}$')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user_type', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('BOTH', 'Both Buyer and Seller')], default='BUYER', max_length=10)),
                ('region', models.CharField(blank=True, choices=[('ASHANTI', 'Ashanti'), ('BRONG_AHAFO', 'Brong Ahafo'), ('CENTRAL', 'Central'), ('EASTERN', 'Eastern'), ('GREATER_ACCRA', 'Greater Accra'), ('NORTHERN', 'Northern'), ('UPPER_EAST', 'Upper East'), ('UPPER_WEST', 'Upper West'), ('VOLTA', 'Volta'), ('WESTERN', 'Western'), ('SAVANNAH', 'Savannah'), ('BONO_EAST', 'Bono East'), ('AHAFO', 'Ahafo'), ('WESTERN_NORTH', 'Western North'), ('NORTH_EAST', 'North East'), ('OTI', 'Oti')], max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('is_verified_seller', models.BooleanField(default=False, help_text='Admin-approved verified seller')),
                ('verification_documents', models.FileField(blank=True, help_text='ID or business registration documents', null=True, upload_to='verification_docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email/phone verified')),
                ('is_staff', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('last_password_change', models.DateTimeField(auto_now_add=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('payment_provider_id', models.CharField(blank=True, help_text='Payment gateway customer ID', max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'), models.Index(fields=['user_type'], name='users_user_user_ty_4573bb_idx'), models.Index(fields=['is_verified_seller'], name='users_user_is_veri_97501b_idx')],
            },
        ),
    ]
